export const GET_IS_USER_EXISTS_REQUEST = "GET_IS_USER_EXISTS_REQUEST";
export const GET_IS_USER_EXISTS_SUCCESS = "GET_IS_USER_EXISTS_SUCCESS";
export const GET_IS_USER_EXISTS_ERROR = "GET_IS_USER_EXISTS_ERROR";
export const SET_IS_USER_EXISTS = "SET_IS_USER_EXISTS";
export const SET_USER_ID = "SET_USER_ID";
