export default [
  {
    ItemName: "item1",
    ItemPrice: "100",
    ItemDescription: "Description for item1",
    Images: [
      require("./_mockItemImg1.jpg"),
      require("./_mockItemImg2.jpg"),
      require("./_mockItemImg3.jpg"),
    ],
    key: "111",
  },
  {
    ItemName: "item2",
    ItemPrice: "200",
    ItemDescription: "Description for item2",
    Images: [
      require("./_mockItemImg1.jpg"),
      require("./_mockItemImg2.jpg"),
      require("./_mockItemImg3.jpg"),
    ],
    key: "222",
  },
  {
    ItemName: "item3",
    ItemPrice: "300",
    ItemDescription: "Description for item3",
    Images: [
      require("./_mockItemImg1.jpg"),
      require("./_mockItemImg2.jpg"),
      require("./_mockItemImg3.jpg"),
    ],
    key: "333",
  },
  {
    ItemName: "item4",
    ItemPrice: "400",
    ItemDescription: "Description for item4",
    Images: [
      require("./_mockItemImg1.jpg"),
      require("./_mockItemImg2.jpg"),
      require("./_mockItemImg3.jpg"),
    ],
    key: "444",
  },
  {
    ItemName: "item5",
    ItemPrice: "500",
    ItemDescription: "Description for item5",
    Images: [
      require("./_mockItemImg1.jpg"),
      require("./_mockItemImg2.jpg"),
      require("./_mockItemImg3.jpg"),
    ],
    key: "555",
  },
  {
    ItemName: "item6",
    ItemPrice: "600",
    ItemDescription: "Description for item6",
    Images: [
      require("./_mockItemImg1.jpg"),
      require("./_mockItemImg2.jpg"),
      require("./_mockItemImg3.jpg"),
    ],
    key: "666",
  },
  {
    ItemName: "item6",
    ItemPrice: "600",
    ItemDescription: "Description for item6",
    Images: [
      require("./_mockItemImg1.jpg"),
      require("./_mockItemImg2.jpg"),
      require("./_mockItemImg3.jpg"),
    ],
    key: "766",
  },
  {
    ItemName: "item6",
    ItemPrice: "600",
    ItemDescription: "Description for item6",
    Images: [
      require("./_mockItemImg1.jpg"),
      require("./_mockItemImg2.jpg"),
      require("./_mockItemImg3.jpg"),
    ],
    key: "866",
  },
  {
    ItemName: "item6",
    ItemPrice: "600",
    ItemDescription: "Description for item6",
    Images: [
      require("./_mockItemImg1.jpg"),
      require("./_mockItemImg2.jpg"),
      require("./_mockItemImg3.jpg"),
    ],
    key: "966",
  },
  {
    ItemName: "item6",
    ItemPrice: "600",
    ItemDescription: "Description for item6",
    Images: [
      require("./_mockItemImg1.jpg"),
      require("./_mockItemImg2.jpg"),
      require("./_mockItemImg3.jpg"),
    ],
    key: "616",
  },
  {
    ItemName: "item6",
    ItemPrice: "600",
    ItemDescription: "Description for item6",
    Images: [
      require("./_mockItemImg1.jpg"),
      require("./_mockItemImg2.jpg"),
      require("./_mockItemImg3.jpg"),
    ],
    key: "626",
  },
  {
    ItemName: "item6",
    ItemPrice: "600",
    ItemDescription: "Description for item6",
    Images: [
      require("./_mockItemImg1.jpg"),
      require("./_mockItemImg2.jpg"),
      require("./_mockItemImg3.jpg"),
    ],
    key: "636",
  },
  {
    ItemName: "item6",
    ItemPrice: "600",
    ItemDescription: "Description for item6",
    Images: [
      require("./_mockItemImg1.jpg"),
      require("./_mockItemImg2.jpg"),
      require("./_mockItemImg3.jpg"),
    ],
    key: "646",
  },
  {
    ItemName: "item6",
    ItemPrice: "600",
    ItemDescription: "Description for item6",
    Images: [
      require("./_mockItemImg1.jpg"),
      require("./_mockItemImg2.jpg"),
      require("./_mockItemImg3.jpg"),
    ],
    key: "656",
  },
  {
    ItemName: "item6",
    ItemPrice: "600",
    ItemDescription: "Description for item6",
    Images: [
      require("./_mockItemImg1.jpg"),
      require("./_mockItemImg2.jpg"),
      require("./_mockItemImg3.jpg"),
    ],
    key: "6676",
  },
  {
    ItemName: "item6",
    ItemPrice: "600",
    ItemDescription: "Description for item6",
    Images: [
      require("./_mockItemImg1.jpg"),
      require("./_mockItemImg2.jpg"),
      require("./_mockItemImg3.jpg"),
    ],
    key: "668",
  },
  {
    ItemName: "item6",
    ItemPrice: "600",
    ItemDescription: "Description for item6",
    Images: [
      require("./_mockItemImg1.jpg"),
      require("./_mockItemImg2.jpg"),
      require("./_mockItemImg3.jpg"),
    ],
    key: "669",
  },
  {
    ItemName: "item6",
    ItemPrice: "600",
    ItemDescription: "Description for item6",
    Images: [
      require("./_mockItemImg1.jpg"),
      require("./_mockItemImg2.jpg"),
      require("./_mockItemImg3.jpg"),
    ],
    key: "166",
  },
  {
    ItemName: "item6",
    ItemPrice: "600",
    ItemDescription: "Description for item6",
    Images: [
      require("./_mockItemImg1.jpg"),
      require("./_mockItemImg2.jpg"),
      require("./_mockItemImg3.jpg"),
    ],
    key: "662",
  },
  {
    ItemName: "item6",
    ItemPrice: "600",
    ItemDescription: "Description for item6",
    Images: [
      require("./_mockItemImg1.jpg"),
      require("./_mockItemImg2.jpg"),
      require("./_mockItemImg3.jpg"),
    ],
    key: "6614",
  },
];
