const RADIUS = 1000;
const MEASURE_UNIT = 0;
const FETCH_PROVIDERS_INTERVAL_TIME = 3000;
const FETCH_PROVIDERS_INTERVAL_RADIUS = 100;

let locationConfig = {
  RADIUS,
  MEASURE_UNIT,
  FETCH_PROVIDERS_INTERVAL_TIME,
  FETCH_PROVIDERS_INTERVAL_RADIUS,
};

export default locationConfig;
